### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by ghost** [pdx-labs/pdx#3]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/pdx-labs/pdx/blob/355027c89f6de7463ceabc6d698452ad7a4fa742/src/pdx/models/anthropic/completion.py#L24C23-L24C23

---

Would love to know if this might help - https://github.com/BerriAI/litellm

~Simple I/O library, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by ghost** [comment]
@krish-adi

**Comment by krish-adi** [comment]
@krrishdholakia PDX don't use any of the client libraries, as it calls the API directly. Under the hood PDX already has homogenization and standardization of calls implemented.
